// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1lgoojkKmyAcSo40U8CTrgXTeEapcqIY',
    appId: '1:261213824970:web:0c85c02e1af876603bd133',
    messagingSenderId: '261213824970',
    projectId: 'flutter-firebase-trainin-4ba3e',
    authDomain: 'flutter-firebase-trainin-4ba3e.firebaseapp.com',
    storageBucket: 'flutter-firebase-trainin-4ba3e.firebasestorage.app',
    measurementId: 'G-58SKPDJ7Y0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmgdvc1vrp50aPFqSNXKwIunw5QflcjQY',
    appId: '1:261213824970:android:9c0c2adbf12362403bd133',
    messagingSenderId: '261213824970',
    projectId: 'flutter-firebase-trainin-4ba3e',
    storageBucket: 'flutter-firebase-trainin-4ba3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhJ7gxyJB22lPTuFoirZQpGa-eYT-S7Mk',
    appId: '1:261213824970:ios:3eae6ddff5d824673bd133',
    messagingSenderId: '261213824970',
    projectId: 'flutter-firebase-trainin-4ba3e',
    storageBucket: 'flutter-firebase-trainin-4ba3e.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseTraining',
  );
}
